### ISSUE TITLE
Issue with å ä ö

### ISSUE THREAD

**Issue by CrallH** [Miicroo/ha-swedish_calendar#1]
Have some issues with the special days and å ä ö. It works on the weekdays, Lördag for example. 
![Screenshot_20200509_001646_io homeassistant companion android](https://user-images.githubusercontent.com/32394267/81453740-af40df00-918a-11ea-9462-d5fc171372bd.jpg)

**Comment by Miicroo** [comment]
Seems that specialThemes.json contained some funky characters. Pushed a new version some time ago, is the problem still there if you reinstall @CrallH ?
