### ISSUE TITLE
Theme day error in log

### ISSUE THREAD

**Issue by CrallH** [Miicroo/ha-swedish_calendar#10]
Hi!

I get this error in the log everytime i reboot:

2022-02-09 10:23:41 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in async_update_ha_state
raise NoEntitySpecifiedError(
homeassistant.exceptions.NoEntitySpecifiedError: No entity id specified for entity Swedish Calendar theme day

Is this something i can fix my self?

**Comment by Miicroo** [comment]
@CrallH I have been debugging this for ages now, I keep getting it on my own system every now and then. Will try to put some effort in and see if I can find out why. Last try was to override the `entity_id()` but that caused other more serious issues

**Comment by Miicroo** [comment]
Finally understood the problem, it seems that fetching the data and calling the update method in HA is fast, so the sensor entity is not yet registered. The correct way to fetch the data would be with a `DataUpdateCoordinator` (which I will have to implement in #11 ), but for now I will do a quick fix and just wait a few seconds with the initial value load

**Comment by Miicroo** [comment]
And of course I found the `async_added_to_hass`-method today after implemented the hack yesterday, updated the code accordingly on master now. `  async_added_to_hass` description: `Called when an entity has their entity_id and hass object assigned, ... Example uses: restore the state`, so this fits perfectly. Could even remove some calls.

**Comment by CrallH** [comment]
Awsome work!!
