### ISSUE TITLE
Sensors not updating 

### ISSUE THREAD

**Issue by jsk-sct** [Miicroo/ha-swedish_calendar#18]
Hi again :(
It seems like sensors doesn't update when the day changes. They update if you restart HA but not when the date changes at midnight:
![image](https://user-images.githubusercontent.com/85673626/200160153-8e36c636-9f67-4042-9120-99392f1a0168.png)

I can't find any error log regarding the integration this time so I imagine it could be a little bit harder to troubleshoot.
Tell if me if you want me to do anything else, I haven't debugged anything before in HA but as long as I get an easy description on what to do and what to look for I'll manage.

/Johan

**Comment by Miicroo** [comment]
I get the same error after a restart, it seems that faboul.se does have some problems with their certificate, it is possible that is has expired. I will see if I can contact them in any way and also check if their is a problem in the integration meanwhile they work on their cert issue

**Comment by churtbeullar** [comment]
Hey.
Same for me. But the entites or not working at all after re-installing the addon. I found this in the logg tho. Could it be something wrong with the API?
Felet härrör från en anpassad integration.

Logger: custom_components.swedish_calendar.provider
Source: custom_components/swedish_calendar/provider.py:39
Integration: Swedish calendar (documentation)
First occurred: 09:21:29 (1 occurrences)
Last logged: 09:21:29

Error when calling: https://sholiday.faboul.se/dagar/v2.1/2022/11/6, Cannot connect to host sholiday.faboul.se:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')]

**Comment by Miicroo** [comment]
@jsk-sct @churtbeullar faboul.se has fixed their SSL issue now, I will look into why the sensors don't update properly

**Comment by Miicroo** [comment]
@jsk-sct @churtbeullar Fix released in v2.0.2, their was a call to set up coordinator listeners missing. Added debug prints as well in my test environment and looks to be working, but can confirm earliest tomorrow 🙂

**Comment by jsk-sct** [comment]
@Miicroo Great. Have downloaded it now and will notify what happens tomorrow to see if it works again.
Either way, good job.

**Comment by jsk-sct** [comment]
![Screenshot_2022-11-07-07-19-37-78_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/85673626/200239318-279c3fcb-f3c5-48b4-beca-a9c767b7f5b4.jpg)
👍 (sorry for mobile screenshot)

**Comment by Miicroo** [comment]
Woo, that does look better! :partying_face:
