### ISSUE TITLE
Downloads the data, most sensors get Unknown

### ISSUE THREAD

**Issue by oidsaasd** [Miicroo/ha-swedish_calendar#37]
I get a warning in the logs

2024-02-10 16:12:27.176 WARNING (MainThread) [custom_components.swedish_calendar.api_data] Error when calling: https://sholiday.faboul.se/dagar/v2.1/2024/2, 

All sensors (like sensor.swedish_calendar_name_day) gets the value unknown.
But I can see that the .cache folder gets updated.

Running latest of everything (inkl 2024.2.1)

**Comment by Miicroo** [comment]
@oidsaasd Tried to check my installation if there was a common error but couldn't find anything obvious. What does the 2 most recent files in .cache look like? My suspicion is that the integration might cache incorrect data, like errors, but hard to verify on my own

**Comment by oidsaasd** [comment]
There must have been some glitches in my installation over the weekend because I now get the proper values. Or at least the values in the fields that I use. sensor.swedish_calendar_eve, sensor.swedish_calendar_flag_day, sensor.swedish_calendar_holiday still shows unknown.

If it a way to trigger refresh of the data? It would be easer to check logs if you know when the fetch happens.

![swedish_holiday](https://github.com/Miicroo/ha-swedish_calendar/assets/15064482/8f6eb041-b339-4f02-83c4-8bc490ff0f46)

**Comment by Miicroo** [comment]
There isn't any manual way to refetch or reload (yet, but will be when it supports loading from UI). However the values seem to be correct, if the API doesn't return a value for a sensor (like holiday) it will get the state `unknown`. I use conditional-card in the UI to omit the field/badge if state is unknown.

I will keep an eye out for errors when calling sholiday too, it feels like it could be a potential bug there

**Comment by elji-lennart** [comment]
I also had problem with unknown name_day, It seems to come after restart of Home Assistant. 

![namnsdag_unknown](https://github.com/Miicroo/ha-swedish_calendar/assets/25637265/852e8a92-c435-4aca-952b-538906f51d1e)

**Comment by oidsaasd** [comment]
Mine seems stabile now again, but posting the history and graph for reference

entity_id,state,last_changed
sensor.swedish_calendar_name_day,Disa,Hjördis,2024-02-03T16:48:39.326Z
sensor.swedish_calendar_name_day,Ansgar,Anselm,2024-02-03T23:00:18.606Z
sensor.swedish_calendar_name_day,Agata,Agda,2024-02-04T23:00:02.882Z
sensor.swedish_calendar_name_day,Dorotea,Doris,2024-02-05T23:00:24.495Z
sensor.swedish_calendar_name_day,Rikard,Dick,2024-02-06T23:00:02.825Z
sensor.swedish_calendar_name_day,Berta,Bert,2024-02-07T23:00:03.106Z
**sensor.swedish_calendar_name_day,unknown,2024-02-08T05:54:54.647Z**
sensor.swedish_calendar_name_day,Fanny,Franciska,2024-02-08T23:00:06.697Z
**sensor.swedish_calendar_name_day,unknown,2024-02-09T10:00:56.963Z**
sensor.swedish_calendar_name_day,Yngve,Inge,2024-02-10T23:00:12.824Z
sensor.swedish_calendar_name_day,Evelina,Evy,2024-02-11T23:00:14.720Z
sensor.swedish_calendar_name_day,Agne,Ove,2024-02-12T23:00:00.867Z

![Snap2](https://github.com/Miicroo/ha-swedish_calendar/assets/15064482/64f2b9a1-3c95-4411-a6f4-826de10a8262)

**Comment by Miicroo** [comment]
I will run some tests against when/how cache is updated, since this is the function that should prevent errors like this. Will get back to you when I have the results

**Comment by Lavve** [comment]
+1 on this one, I get "Unknown" after restart for what I can see

![image](https://github.com/Miicroo/ha-swedish_calendar/assets/302588/0b99fd67-634a-4498-afbc-8cd6031b74e8)

**Comment by Miicroo** [comment]
@Lavve That is indeed odd! Do you also use the caching functionality? And the cache file for february looks ok? (It is one of the most recently changed).
Any errors in the logs?

**Comment by Lavve** [comment]
@Miicroo thanks for quick response. I'm fairly new to HA, and have no insight in how caching functionality works. Also my logs for  "Names celebrated" is empty.

**Comment by Miicroo** [comment]
@Lavve It might be that the sensor is slow in fetching data from the api, possibly there might be timeouts. There is a way to configure the integration to download the data beforehand , so if you for instance dont have internet atm, it will still work. Here is the documentation, https://github.com/Miicroo/ha-swedish_calendar?tab=readme-ov-file#cache, do you know if you added this to your config when you set up the integration?

The enabled True part is the most important

**Comment by Lavve** [comment]
@Miicroo It was not added to my config. I've set it to True now, and I got some data to the .cache folder after restart, but only for the days specified in `days_after_today`, not `days_before_today`. So todays data is still empty, but hopefully it will be correct by tomorrow.

**Comment by Miicroo** [comment]
@Miicroo Hope it helps! Out of curiosity, are all your sensor values unknown or is it just the name_day? Since it is Feb 29, and it only occurs every 4th year, there is no namnsdag today. So the value being unknown is actually correct. I could see from your image that it has happened on other days though, so might still be an issue

**Comment by Lavve** [comment]
@Miicroo There are more sensors that is `unknown`, but not all of them:

![image](https://github.com/Miicroo/ha-swedish_calendar/assets/302588/a0714148-8ac6-4a35-9a3a-d5aa60a8f546)

**Comment by Miicroo** [comment]
@Lavve If you check the logs (settings > systems > logs, or Inställningar > System > Loggar if you use Swedish), can you see any errors regarding swedish_calendar or faboul? Feels like there are way to few values present

**Comment by Lavve** [comment]
@Miicroo here's the error log looking for `faboul`

> This error originated from a custom integration.
> 
> Logger: custom_components.swedish_calendar.api_data
> Source: custom_components/swedish_calendar/api_data.py:33
> Integration: Swedish calendar (documentation)
> First occurred: 13:24:14 (1 occurrences)
> Last logged: 13:24:14
> 
> Error when calling: https://sholiday.faboul.se/dagar/v2.1/2024/2,

**Comment by Miicroo** [comment]
Performed some tests today and it seems that sometimes the API calls indeed fail due to timeouts. Implemented a fix with retries, so that it will make a first call to the API with a timeout of 10 seconds, second call with 20 seconds, and finally a third one with 30 seconds. If there is still no response from the API we will move ahead with the rest of the setup, and this will be considered a failure on the API side (which can happen, it is just not something we can control). Hoping this, in combination with the cache functionality, will remove the problems with the unknown values.

**Comment by Miicroo** [comment]
@oidsaasd @elji-lennart @Lavve There is now a v2.5.1 out. Tested it on my own system and actually got `Timeout when calling: https://sholiday.faboul.se/dagar/v2.1/2024/2`, and I could then see that it retried and succeeded. If you see any problems with the new version, please let me know.

**Comment by Lavve** [comment]
@Miicroo downloaded v2.5.1 yesterday, which I regret because now I don't know if it was that or the cache that made it work. 😄 
Anyway, today I got the correct values in all entities again, even after restart of HA.

Thank you for your quick responses and fix on this issue.

**Comment by Miicroo** [comment]
Closing for now, update/reopen if problem persists!
