### ISSUE TITLE
No entity id specified for entity Swedish Calendar theme day

### ISSUE THREAD

**Issue by Miicroo** [Miicroo/ha-swedish_calendar#4]
HomeAssistant 0.118.2
Annoying error to get on start up, however, no functionality seems to be impacted.

**Logginformation (ERROR)**
Logger: homeassistant
Source: helpers/entity.py:271
First occurred: 16:32:43 (1 occurrences)
Last logged: 16:32:43

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 271, in async_update_ha_state
    raise NoEntitySpecifiedError(
homeassistant.exceptions.NoEntitySpecifiedError: No entity id specified for entity Swedish Calendar theme day

**Comment by T-h-o-m-a-s** [comment]
Did you try this?
https://www.home-assistant.io/docs/configuration/templating/

"Avoid using states.sensor.temperature.state, instead use states('sensor.temperature'). It is strongly advised to use the states(), is_state(), state_attr() and is_state_attr() as much as possible, to avoid errors and error message when the entity isn’t ready yet (e.g., during Home Assistant startup)."

**Comment by Miicroo** [comment]
@T-h-o-m-a-s Nice catch, I had not thought about the automation! :) Updating examples (as well as my own system), thanks!
