### ISSUE TITLE
Log warnings since HA Core 2024.08

### ISSUE THREAD

**Issue by henrikbla** [Miicroo/ha-swedish_calendar#41]
Let me know if any additional information is needed.

Detected blocking call to open with args ('/config/custom_components/swedish_calendar/.cache/12c8594c421c9069f18dd7f70024d554.json',) inside the event loop by custom integration 'swedish_calendar' at custom_components/swedish_calendar/api_data.py, line 127: with open(path) as cached_file: (offender: /config/custom_components/swedish_calendar/api_data.py, line 127: with open(path) as cached_file:), please report it to the author of the 'swedish_calendar' custom integration For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 461, in _async_setup_component await asyncio.gather( File "/usr/src/homeassistant/homeassistant/setup.py", line 463, in <genexpr> create_eager_task( File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 752, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/swedish_calendar/__init__.py", line 50, in async_setup_entry await data_coordinator.async_refresh() File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 330, in async_refresh await self._async_refresh(log_failures=True) File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh self.data = await self._async_update_data() File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 271, in _async_update_data return await self.update_method() File "/config/custom_components/swedish_calendar/coordinator.py", line 65, in update_data self._cache = await self._get_calendars() File "/config/custom_components/swedish_calendar/coordinator.py", line 88, in _get_calendars swedish_dates = await self._api_data_provider.fetch_data(start_date, end_date) File "/config/custom_components/swedish_calendar/api_data.py", line 40, in fetch_data json_data = await self._get_json_from_url(url, tries*10) File "/config/custom_components/swedish_calendar/api_data.py", line 77, in _get_json_from_url data = self._cache.get(url) File "/config/custom_components/swedish_calendar/api_data.py", line 127, in get with open(path) as cached_file:
Detected blocking call to open with args ('/config/custom_components/swedish_calendar/specialThemes.json', 'w') inside the event loop by custom integration 'swedish_calendar' at custom_components/swedish_calendar/theme_data.py, line 59: with open(self._config.path, 'w') as themes_file: (offender: /config/custom_components/swedish_calendar/theme_data.py, line 59: with open(self._config.path, 'w') as themes_file:), please report it to the author of the 'swedish_calendar' custom integration For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 330, in async_refresh await self._async_refresh(log_failures=True) File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh self.data = await self._async_update_data() File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 271, in _async_update_data return await self.update_method() File "/config/custom_components/swedish_calendar/coordinator.py", line 61, in update_data await self._theme_data_updater.update() File "/config/custom_components/swedish_calendar/theme_data.py", line 59, in update with open(self._config.path, 'w') as themes_file:

**Comment by Miicroo** [comment]
Thank you for the bug report! I checked the documentation and there are a few calls scattered all over the code base that needs fixing. Will take some days, but will release as soon as there is a working version!

**Comment by Miicroo** [comment]
@henrikbla Issue should now be fixed, and part of release 3.0.1! I have tested and it works fine in my local environment, but since the integration has lots of different settings I might have missed some corner case, so please let me know if there are any more errors that you find.
