### ISSUE TITLE
No 'version' key in the manifest file

### ISSUE THREAD

**Issue by fredamn76** [Miicroo/ha-swedish_calendar#5]
No 'version' key in the manifest file for custom integration 'swedish_calendar'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'swedish_calendar'

**Comment by jhqv** [comment]
Quote from https://developers.home-assistant.io/docs/creating_integration_manifest/#version:

> The version of the integration is required for custom integrations. The version needs to be a valid version recognized by AwesomeVersion like CalVer or SemVer.

**Comment by Miicroo** [comment]
@fredamn76 @jhqv Fixed in [c76773d862c90e1c530c04b0bcd801549d7b557a](https://github.com/Miicroo/ha-swedish_calendar/commit/c76773d862c90e1c530c04b0bcd801549d7b557a), available on master. Thank you for the heads up!
