### ISSUE TITLE
When no Swedish Theme day specified - sensor keeps last days value

### ISSUE THREAD

**Issue by T-h-o-m-a-s** [Miicroo/ha-swedish_calendar#6]
When there is no theme day specified for a particular day, the sensor is not updated to "" or blank or "-". Instead the previous days theme is kept. 
It would be good if the sensor senses that there is no theme that day and makes the sensor blank/empty or "No theme today".

**Comment by Miicroo** [comment]
Thanks for the bug report! Fixed and merged now 😃
