### ISSUE TITLE
Adding months

### ISSUE THREAD

**Issue by osse-andreas** [Miicroo/ha-swedish_calendar#9]
It would be nice if you could add a sensor with the months :)

**Comment by Miicroo** [comment]
I think the best way to achieve this would instead be to use a template sensor, that way it will be fully supported by HomeAssistant and not fail if this integration happens to fail

Example for month value/number:
```
- sensor:
  - name: "Current month"
    state: {{ now().month }}
```

Example for month name:
```
- sensor:
  - name: "Current month name"
    state: {{ ['Januari', 'Februari', 'Mars', 'April', 'Maj', 'Juni', 'Juli', 'Augusti', 'September', 'Oktober', 'November', 'December'][now().month-1] }}
```
